export const operationalVocabulary = {
  entry: [
    "chegou",
    "chegaram",
    "entrou",
    "entraram",
    "recebi",
    "recebemos",
    "adicionar",
    "adicione",
    "adiciona",
    "inclui",
    "incluir",
    "colocar",
    "coloquei",
    "comprou",
    "comprei",
    "compramos",
    "entrega",
    "entregaram",
    "lancar",
    "lancei",
    "registrar",
    "registrei",
    "repor",
    "reposicao",
    "abastecer",
    "abasteceu"
  ],
  exit: [
    "saiu",
    "sairam",
    "saida",
    "vendeu",
    "vende",
    "venda",
    "vendi",
    "vendemos",
    "venderam",
    "baixou",
    "baixa",
    "baixar",
    "dei baixa",
    "dar baixa",
    "retirar",
    "retirei",
    "retirada",
    "tirar",
    "tirei",
    "usei",
    "usou",
    "consumiu"
  ],
  zero: [
    "zerou",
    "zera",
    "zerar",
    "zerado",
    "acabou",
    "acabaram",
    "esgotou",
    "esgotaram",
    "terminou",
    "terminaram",
    "saiu tudo",
    "vendeu tudo",
    "acabou tudo",
    "acabaram tudo",
    "nao tem mais"
  ],
  expiration: [
    "vence",
    "vencem",
    "vencimento",
    "validade",
    "valido ate",
    "vence em",
    "venc",
    "val"
  ],
  packaging: [
    "unidade",
    "unidades",
    "un",
    "unds",
    "garrafa",
    "garrafas",
    "pet",
    "pets",
    "lata",
    "latas",
    "latinha",
    "latinhas",
    "fardo",
    "fardos",
    "fd",
    "pack",
    "packs",
    "caixa",
    "caixas",
    "cx",
    "pacote",
    "pacotes",
    "pct",
    "engradado",
    "engradados"
  ]
} as const;

export type VocabularyGroup = keyof typeof operationalVocabulary;
